-- Atribui a senha da role de login da aplicacao.
--
-- Nao e migration versionada, e a distincao importa: senha nao e schema. Se
-- fosse `V...`, o valor entraria no checksum e trocar a senha exigiria
-- `repair`. Como callback `afterMigrate`, roda a cada execucao do servico de
-- migracao e a rotacao e so trocar o segredo e subir de novo.
--
-- O valor nunca esta neste arquivo: chega como placeholder do Flyway, e quem o
-- preenche le o arquivo montado (`docker/migracao/entrypoint.sh`). E o mesmo
-- caminho que a senha do proprio Flyway ja percorre, e pela mesma razao — a
-- secao 7 de `infra/docker/architecture.md` recusa segredo em variavel de
-- ambiente, porque variavel vaza em `docker inspect`.
ALTER ROLE kanban_app PASSWORD '${senha_aplicacao}';
